---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
  - update
- apiGroups:
  - sample.a2ush.dev.a2ush.dev
  resources:
  - sampleobjects
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sample.a2ush.dev.a2ush.dev
  resources:
  - sampleobjects/finalizers
  verbs:
  - update
- apiGroups:
  - sample.a2ush.dev.a2ush.dev
  resources:
  - sampleobjects/status
  verbs:
  - get
  - patch
  - update
