# permissions for end users to view sampleobjects.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: sampleobject-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: guideline-for-kubernetescustomresource
    app.kubernetes.io/part-of: guideline-for-kubernetescustomresource
    app.kubernetes.io/managed-by: kustomize
  name: sampleobject-viewer-role
rules:
- apiGroups:
  - sample.a2ush.dev.a2ush.dev
  resources:
  - sampleobjects
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - sample.a2ush.dev.a2ush.dev
  resources:
  - sampleobjects/status
  verbs:
  - get
